controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_send_email:
    path: '/enviar-email/{tarefaId}'
    controller: App\Controller\EmailController::sendEmail



app_anexo_delete:
    path: /anexo/{id}
    controller: App\Controller\AnexoController::delete
    methods: POST

# config/routes.yaml

app_anexo_show:
    path: /anexo/show/{id}
    controller: App\Controller\AnexoController::show



 

